### ISSUE TITLE
Move to Python3

### ISSUE THREAD

**Issue by rgardner** [project-nikola/automation#10]
## Why?
Python3 is more efficient for many builtins (uses generators instead of the iterators. It has better string support (helpful for hardware projects), has great type annotations (for code readability), and it will only become more popular over the next several years.

## TODO
- [x] do all libraries support it?
- [x] run python2to3
- [x] test with live data

All libraries supported!
1. ~~nose==1.3.4~~
2. ~~setuptools==7.0~~
3. ~~parse==1.6.6~~
4. ~~pymongo==2.7.2~~
5. ~~pyserial==2.7~~
6. ~~xbee==2.1.0~~

Now, just run python2to3 and adapt for python3.

**Comment by rgardner** [comment]
I plan to add type annotations over time, but for now, this issue is closed.
